### ISSUE TITLE
Terraform.output() has incomplete implementation

### ISSUE THREAD

**Issue by sammck** [beelit94/python-terraform#22]
The "output" command has a few problems:

1) It does not support the case where "name" is omitted, which allows you to fetch all outputs as a single dictionary
2) It does not return the "type" attribute of the output and it maps any value to type "string" rather than respecting the "type" attribute.
3) It does not return the "sensitive" attribute.
4) It provides no way to determine the return code or see stderr text when an error occurs--it simply returns None on error.
5) It does not conform to the (ret_code, out, err) tuple response mechanism that is documented to be common for all commands

At this point, for backwards compatibility, it is too late to make it conform to standard return value conventions for commands. But at least we could do the following:

1) Add an output_command() method that conforms to return value conventions.
2) allow "name" to be optional or None, in which case the entire return document would be parsed by json.loads and returned.
3) Add an optional raise_on_error boolean parameter that would allow error info to be optionally returned by exception.

If you would like me to contribute a solution you can add me to the contributors list...

**Comment by beelit94** [comment]
Hi @sammck, it's been a while since I check the output function. So I need some time to look into it. But yes, I would love to add you as a cooperator of this repo. I'm still lack of "how to release" doc, except that, if you're familiar with pytest and travis ci then you're good to go.

**Comment by sammck** [comment]
@beelit94 I got purest working ok, except I am running terraform v0.10.7 which generates a different expected output for "plan". I don't want to downgrade terraform. What do you prefer: a) update everybody to current terraform, or b: support multiple alternative expected outputs?

**Comment by sammck** [comment]
fyi I submitted a pull request, which is breaking because of tf v0.10.7 dependency in test...

**Comment by sammck** [comment]
This issue is resolveed for me with pull request https://github.com/beelit94/python-terraform/pull/24
