### ISSUE TITLE
passing ssh private key to terraform 

### ISSUE THREAD

**Issue by narasimha18sv** [beelit94/python-terraform#26]
How to pass ssh private key data to terraform script ?

if i read the id_rsa key generated already I cannot place it inside the file. 

My code is creating a terrafrom module file. for example
module "consul" {
  source  = "hashicorp/consul/aws"
  servers = 3
}
Like above I am passing my private key. but facing issues as private key as it contains \n(new line)

How to I resolve this. Please let me know

**Comment by beelit94** [comment]
@narasimha18sv I'm not quite understand what you're trying to achieve,
I'm looking at https://registry.terraform.io/modules/hashicorp/consul/aws/0.0.5?tab=inputs
and it doesn't require you to input your private key, but only name of the key pair.

Could you provide more detailed example?
Usually only the public key is the one we need to give it away, not the private key.
If you're trying to ssh access through python, that would be out of scope of this python library :)

**Comment by sammck** [comment]
Perhaps the question is simply how to pass a multi line string in a terraform config file. This is a general terraform HCL question unrelated to python-terraform, but here is the answer:

Multiline strings can use shell-style "here doc" syntax, with the string starting with a marker like <<EOF and then the string ending with EOF on a line of its own. The lines of the string and the end marker must not be indented.

**Comment by beelit94** [comment]
@narasimha18sv closing for now, feel free to reopen if needed
