### ISSUE TITLE
var_file doesn't support hcl

### ISSUE THREAD

**Issue by automaticgiant** [beelit94/python-terraform#28]
correct if wrong, but would be nice to use existing `tfvars` files.
was unable to `tf = Terraform(var_file='pathtotfvarsfile')`
UPDATE
the plot thickens (after i moved it)
```
-F__init__.py                284 WARNING  error: invalid value "presets/stsdev.tfvars" for flag -var-file: Error reading presets/stsdev.tfvars: open presets/stsdev.tfvars: no such file or directory
```
i guess it just reads it and ignores it then?

right now i'm actually using    `ret, out, err = tf.plan('-var-file=presets/stsdev-dms.tfvars')`

i guess that means this doesn't matter, but it might warrant a mention in the docs.
UPDATE
started doing `ret, out, err = tf.plan(var_file='presets/stsdev-dms.tfvars', state='-')` after reading more source.

**Comment by beelit94** [comment]
@automaticgiant can you give us the example of your tf file and var file? what's the terraform version you're using?
tf = Terraform(var_file='pathtofvarsfile') should be working fine from my testing

**Comment by beelit94** [comment]
@automaticgiant closed the ticket for now, feel free to reopened if needed
