### ISSUE TITLE
unable to get output from validate

### ISSUE THREAD

**Issue by automaticgiant** [beelit94/python-terraform#29]
both come out empty, and can't get output from `capture_output=False` either.
```
from python_terraform import Terraform

NO_CHANGES = 'No changes.'

tf = Terraform()


def test_validate():
    vars = {
                redacted stuff that i couldn't get it to read from tfvars file (see #28)
            }
    ret, out, err = tf.validate(var=vars)
    assert 0 is ret
    assert NO_CHANGES in out or NO_CHANGES in err

if __name__ == '__main__':
    test_validate()

```
tried outside pytest to make sure that wasn't stealing the output.
but i can get error output like:
```
WARNING:python_terraform:error: Errors:

  * 1 error(s) occurred:

* Required variable not set: LOB
```
so i guess it seems to be just when it exits 0?

**Comment by beelit94** [comment]
1. capture output should be true to be able to read things from 'out' and 'err'
2. "NO_CHANGES in out" will only be true when you fix the error. which is you missing a variable 'LOB'
3. "NO_CHANGES in err" is not correct, err is for stderr, which will be error message

**Comment by beelit94** [comment]
@automaticgiant I'm closing this ticket, feel free to reopen this if you have any further questions
