### ISSUE TITLE
apply command hangs

### ISSUE THREAD

**Issue by tehremo** [beelit94/python-terraform#31]
I can perform an init() and plan() without issue, but when calling apply() the command never completes. Here is the output after I stop it.

`    print(tf.apply())
  File "/usr/local/lib/python3.6/site-packages/python_terraform/__init__.py", line 103, in apply
    return self.cmd('apply', *args, **option_dict)
  File "/usr/local/lib/python3.6/site-packages/python_terraform/__init__.py", line 277, in cmd
    out, err = p.communicate()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1514, in _communicate
    ready = selector.select(timeout)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)`

**Comment by tehremo** [comment]
Here are the commands I use:
`
tf = Terraform(working_dir=dir_path, var_file=file_name)
    print(tf.init(reconfigure=True))
    print(tf.plan())
    print(tf.apply())
`

This is the output:
(0, '\nInitializing provider plugins...\n\nThe following providers do not have any version constraints in configuration,\nso the latest version was installed.\n\nTo prevent automatic upgrades to new major versions that may contain breaking\nchanges, it is recommended to add version = "..." constraints to the\ncorresponding provider blocks in configuration, with the constraint strings\nsuggested below.\n\n* provider.aws: version = "~> 1.8"\n* provider.template: version = "~> 1.0"\n\nTerraform has been successfully initialized!\n\nYou may now begin working with Terraform. Try running "terraform plan" to see\nany changes that are required for your infrastructure. All Terraform commands\nshould now work.\n\nIf you ever set or change modules or backend configuration for Terraform,\nrerun this command to reinitialize your working directory. If you forget, other\ncommands will detect it and remind you to do so if necessary.\n', '')

(2, 'Refreshing Terraform state in-memory prior to plan...\nThe refreshed state will be used to calculate this plan, but will not be\npersisted to local or remote state storage.\n\ndata.template_file.container_definition: Refreshing state...\n\n------------------------------------------------------------------------\n\nAn execution plan has been generated and is shown below.\nResource actions are indicated with the following symbols:\n  + create\n\nTerraform will perform the following actions:\n\n+ aws_alb_listener_rule.listener_rule\n      id:                                         <computed>\n      action.#:                                   "1"\n      action.0.target_group_arn:                  "${aws_alb_target_group.target_group.arn}"\n      action.0.type:                              "forward"\n      arn:                                        <computed>\n      condition.#:                                "2"\n      condition.3881067798.field:                 "host-header"\n      condition.3881067798.values.#:              "1"\n      condition.3881067798.values.0:              "commercialcredit-approvals-dev.cloud.capitalone.com"\n      condition.4051900450.field:                 "path-pattern"\n      condition.4051900450.values.#:              "1"\n      condition.4051900450.values.0:              "/api/*"\n      listener_arn:                               "arn:aws:elasticloadbalancing:us-east-1:586488143756:listener/app/credit-internal-svcs-dev-alb/e201eec1c4fc48b2/395b244b9e7c984c"\n      priority:                                   "391"\n\n  + aws_alb_target_group.target_group\n      id:                                         <computed>\n      arn:                                        <computed>\n      arn_suffix:                                 <computed>\n      deregistration_delay:                       "60"\n      health_check.#:                             "1"\n      health_check.0.healthy_threshold:           "5"\n      health_check.0.interval:                    "30"\n      health_check.0.matcher:                     "200"\n      health_check.0.path:                        "/ping"\n      health_check.0.port:                        "traffic-port"\n      health_check.0.protocol:                    "HTTP"\n      health_check.0.timeout:                     "5"\n      health_check.0.unhealthy_threshold:         "2"\n      name:                                       "ba-test-dev"\n      port:                                       "80"\n      protocol:                                   "HTTP"\n      stickiness.#:                               <computed>\n      target_type:                                "instance"\n      vpc_id:                                     "vpc-1888f67d"\n\n  + aws_ecs_service.service_with_target_group\n      id:                                         <computed>\n      cluster:                                    "cml-credit-internal-svcs-dev-east"\n      deployment_maximum_percent:                 "200"\n      deployment_minimum_healthy_percent:         "50"\n      desired_count:                              "1"\n      iam_role:                                   "arn:aws:iam::586488143756:role/capone-spr-cmlcreditpinternalservices"\n      launch_type:                                "EC2"\n      load_balancer.#:                            "1"\n      load_balancer.~3858074602.container_name:   "ba-test-dev"\n      load_balancer.~3858074602.container_port:   "30"\n      load_balancer.~3858074602.elb_name:         ""\n      load_balancer.~3858074602.target_group_arn: "${aws_alb_target_group.target_group.arn}"\n      name:                                       "ba-test-dev"\n      task_definition:                            "${aws_ecs_task_definition.task.arn}"\n\n  + aws_ecs_task_definition.task\n      id:                                         <computed>\n      arn:                                        <computed>\n      container_definitions:                      "[{\\"cpu\\":10,\\"dockerLabels\\":{\\"service.BAP\\":\\"bapsomething\\",\\"service.team-name\\":\\"grimlock\\"},\\"environment\\":[{\\"name\\":\\"environment\\",\\"value\\":\\"dev\\"}],\\"essential\\":true,\\"image\\":\\"artifactory.cloud.capitalone.com/fake/news:1\\",\\"memory\\":128,\\"name\\":\\"ba-test-dev\\",\\"portMappings\\":[{\\"containerPort\\":30,\\"hostPort\\":0,\\"protocol\\":\\"tcp\\"}]}]"\n      family:                                     "ba-test-dev"\n      network_mode:                               "bridge"\n      revision:                                   <computed>\nPlan: 4 to add, 0 to change, 0 to destroy.\n\n------------------------------------------------------------------------\n\nNote: You didn\'t specify an "-out" parameter to save this plan, so Terraform\ncan\'t guarantee that exactly these actions will be performed if\n"terraform apply" is subsequently run.\n\n', '')

**Comment by tehremo** [comment]
I got it figured out. I needed to pass in the `-auto-approve` flag via **kwargs:

`
kwargs = {"auto-approve": True}
print(tf.apply(**kwargs))
`

**Comment by dragan1979** [comment]
Can anyone help me with this: https://github.com/beelit94/python-terraform/issues/34

**Comment by dragan1979** [comment]
solved-https://devops.stackexchange.com/questions/3353/create-multiple-ec2-instances-using-python-script-in-loop-iteration

**Comment by AOUES** [comment]
@atkinsonbg i have the same problem, did you change somthing in the init.py ??

**Comment by AOUES** [comment]
Actually it's working in python2 without adding auto-approve option, but in python3 the tf.apply never completes

**Comment by AOUES** [comment]
Solved ! I re-installed python-terraform and it works :)

**Comment by vishal8k** [comment]
This issue is still there in python3 when running `apply` command with `auto-approve`. This issue should be reopened. Re-installing python-terraform didn't work for me.

**Comment by viniciuscoelho** [comment]
I also have this problem with python3. Anyone found the solution?

**Comment by Abhinay-somisetty** [comment]
I was able to perform apply without an issue with auto-approve till last week.. but suddenly it stopped working. Anyone is facing this issue or found the solution for this issue? Thanks.

**Comment by feliperandozup** [comment]
`terraform.apply(skip_plan=True) `
should do the trick

**Comment by FelipeRando** [comment]
`terraform.apply(skip_plan=True) `
should do the trick
