### ISSUE TITLE
how can I use the option "-auto-approve"

### ISSUE THREAD

**Issue by zhujinghui** [beelit94/python-terraform#32]
Hi,

when I invoke tf.apply(), how can I use the option "-auto-approve"?

Thank you.

**Comment by tehremo** [comment]
You can use `**kwargs`:

```
kwargs = {"auto-approve": True}
tf.apply(**kwargs)
```

**Comment by beelit94** [comment]
Please leave this ticket open, I think we already change this to default just not release yet

**Comment by beelit94** [comment]
This is released in 0.10.0 as a default value

**Comment by sanjaysingatalur** [comment]
how do i get to know the version of my python-terraform?

**Comment by sanjaysingatalur** [comment]
i have my commands as below.eventhough i have specified as auto-approve as true its taking as false.Can you please help here.

kwargs = {"auto_approve": True}
t.apply(**kwargs)

when i execute t.apply i could see that -auto-approve is true and false as well and its taking as false ,would be waiting for user's input

terraform apply -var-file=/tmp/tmpti43sy65 -no-color -input=false -auto-approve=true -auto-approve=false

**Comment by sanjaysingatalur** [comment]
and i am using 0.10.0 version

**Comment by jmjolysc** [comment]
@sanjaysingatalur I had the same issue. The `auto_approve` variable is tied to `skip_plan` (see [here](https://github.com/beelit94/python-terraform/blob/99950cb03c37abadb0d7e136452e43f4f17dd4e1/python_terraform/__init__.py#L109)).

So, you must save your plan and then apply it while skipping the plan:
1. `t.plan(out="plan.out")`
2. `t.apply("plan.out", skip_plan=True)`
