### ISSUE TITLE
 No such file or directory: 'terraform'  ???

### ISSUE THREAD

**Issue by devops007** [beelit94/python-terraform#39]
return_code, stdout, stderr = tf.plan()
  File "/home/westos/Django/jumpserver/python3.5/lib/python3.5/site-packages/python_terraform/__init__.py", line 144, in plan
    return self.cmd('plan', *args, **options)
  File "/home/westos/Django/jumpserver/python3.5/lib/python3.5/site-packages/python_terraform/__init__.py", line 276, in cmd
    cwd=working_folder, env=environ_vars)
  File "/usr/lib64/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'terraform'

**Comment by beelit94** [comment]
@devops007 hi, I'm guessing your binary path is not givien,
Could you attach more detail about how you initiate "tf" instance?
there's a parameter "terraform_bin_path" you can give when you init the instance.

**Comment by beelit94** [comment]
@devops007 do you manage to resolve this?

**Comment by beelit94** [comment]
@devops007 closing for now, feel free to reopen it if needed

**Comment by Hayyk** [comment]
I have the same issue. How can I define terraform_bin_path?

**Comment by AOUES** [comment]
I also have the same error, i took the same init as in the exemple but i get this error, some issues to propose ??

**Comment by Hayyk** [comment]
@AOUES you can use this way `tf = Terraform(working_dir='/path/to/your/working/dir', terraform_bin_path='/path/to/terraform-bin')`

**Comment by AOUES** [comment]
@Hayyk i have alredy fixed the problem by the modification of the init function so it consider the binarie path of terraform, thank you for the response

**Comment by dennis-me** [comment]
> @devops007 hi, I'm guessing your binary path is not givien,
> Could you attach more detail about how you initiate "tf" instance?
> there's a parameter "terraform_bin_path" you can give when you init the instance.

Where can I find the terraform_bin_path on linux?

**Comment by AbhishekPattnaik04** [comment]
@AOUES  how did u solve the issue?

**Comment by lsalas300974** [comment]
tf = Terraform(working_dir='/path/to/your/working/dir', terraform_bin_path='/path/to/terraform-bin') works for me, thanks @Hayyk
