### ISSUE TITLE
Multiple Provider in Terraform Not Working as Expected

### ISSUE THREAD

**Issue by Kannancsq** [beelit94/python-terraform#50]
We are using Terraform with Azure, and currently implementing a Python Layer using Python-Terraform Library.

We use multiple provider inside a terraform script, as we have got different Service principal for doing different activities.

Service principal details are stored in Key Vault, and we pass only Key Vault Service Principal to retrieve other Service Principals. First provider service principal works fine as we are passing values from python, for the rest Python-Wrapper function throw error during plan and apply.

Is it possible to use multiple provider using Python-Terraform Wrapper API.

**Comment by Spikeophant** [comment]
I haven't tried this, I will run some tests and look into the code on this.  I actually am getting ready to do a project that will require this so if the support isn't there now I will add it.

**Comment by Spikeophant** [comment]
Can you show me an example of what's not working for you, I am calling tf plans that have multiple providers for varying modules we use without issue.  For example we have route53 DNS in a centralized account, so our modules update DNS in that account while deploying Fargate containers to another account, all seems to work for me without issue.

**Comment by Spikeophant** [comment]
Closing due to lack of information.
