### ISSUE TITLE
Project appears abandoned

### ISSUE THREAD

**Issue by Spikeophant** [beelit94/python-terraform#51]
Hello,

  This project appears abandoned, would anyone be interested in starting a -ng version of this, forking it, and pushing it to pypi pulling in PR's outstanding on this, and working the open buglist?  I'd be happy to do the fork and manage packaging and stuff.

**Comment by beelit94** [comment]
Hi @Spikeophant sorry, I haven't login to GitHub for and worked on terraform project for a while and didn't realize this project still pretty active. Could I add you as a contributor so you can publish the package of this project?

**Comment by Spikeophant** [comment]
Yes that would be awesome, I am using it pretty heavily at work and would be happy to start doing some bug fixes, working ticket,s and reviewing PRs!

**Comment by beelit94** [comment]
Hey @Spikeophant I want to follow up on this, I've added you to the collaborator. You will have the permission to release and publish the python-terraform. That being said, I'm still working on the document on how to publish it, please bear with for 1-2 days. I've been pretty occupied by family and work.

**Comment by Spikeophant** [comment]
No worries, thank you.
