### ISSUE TITLE
python-terraform is not working with Terraform 0.12

### ISSUE THREAD

**Issue by Anbukugan** [beelit94/python-terraform#55]
I have updated my terraform form version 0.11 to 0.12. I tried to execute the terraform script from the python using python-terraform wrapper API. But it shows the following error,

`Error: Argument or block definition required
on C:\Users\vmadmin\AppData\Local\Temp\2\tmpk1c5kkw3 line 1:
   1: {"client_id": "132456789", "client_secret": "welcome", "subscription_id": "098765432", "tenant_id": "0987654321"}
An argument or block definition is required here.`

But yet when I run the same code with terraform version 0.11 it executes fine.

**Comment by Spikeophant** [comment]
Do you have example code?  What resources and providers are you attempting to use?

**Comment by davzucky** [comment]
@Anbukugan This is the same error that I had #54.
@Spikeophant helped me with it. The code that fixes the problem is already checked in, however, we need to wait for the next version of the pip package to be able to pick it up which should happen next week.
I tested the fix and confirmed it works.

**Comment by Anbukugan** [comment]
@davzucky Sorry for the delayed response. I think the 10.0.1 version is available. I will check on it.
@Spikeophant If I face the same issue I will send you the code. Thanks
