### ISSUE TITLE
provider.aws: InvalidClientTokenId

### ISSUE THREAD

**Issue by benjaminpottier** [beelit94/python-terraform#6]
I'm trying to pass credentials to terraform like so:
    
    t.cmd(COMMAND, var=foo)
    
COMMAND is one of 'apply', 'destroy', 'plan', 'refresh'
    
and foo is a dictionary {'access_key':'blah', 'secret_key':'blah'} generated dynamically

if I use foo then I get provider.aws: InvalidClientTokenId: The security token included in the request is invalid. But if I just create a static dictionary with the same generated keys it works fine. Any idea?

**Comment by benjaminpottier** [comment]
never mind ... it was a timing issue (sorry)

**Comment by beelit94** [comment]
@benjaminpottier Thank you for the question. I actually can't figure out what kind of timing issue will result different behavior between static dictionary and dynamic one. Would you mind share more a little bit :) Feel free to close the ticket in anytime

**Comment by benjaminpottier** [comment]
It was just that when I was using the static dictionary I was using credentials that I had already generated. When I used the dynamic dictionary I was trying to use the credentials too soon after generating them, needed to wait about ten seconds before they were valid.
