### ISSUE TITLE
[Question] How i know the current terraform version supported

### ISSUE THREAD

**Issue by mo-saeed** [beelit94/python-terraform#61]
Hello,

Right now i want to use terraform latest version 0.12.6 and I am not sure how to find out if this version supported by python-terraform or not.

**Comment by Spikeophant** [comment]
It should work with 0.12.6, but you'll have to try it and see if there are bugs.  I have not tried on that specific version.

**Comment by efi1** [comment]
@ mo-saeed - could you please update if it works?

**Comment by Spikeophant** [comment]
I'm working on updating the tests for Terraform 0.12 while maintaining tests for 0.11 and below, but everything appears to work fine in the newer versions.  Hashicorp changed the format of some of the command outputs so that is breaking our tests.

**Comment by Spikeophant** [comment]
I am using 0.12.6 for all my testing at this time on my personal machine, and 0.11.7 on my work machine.

**Comment by efi1** [comment]
Thanks!!, I'll check it out.

**Comment by mo-saeed** [comment]
@efi1 yes it works well with me, I am just wondering is it necessary to install terraform on the machine before using python-terrafom ? that's why i asked my question actually

**Comment by Spikeophant** [comment]
Yes this application is dependent upon the system terraform and does not ship with a terraform binary.  WE do not install terraform as part of the installation of python-terraform.
