### ISSUE TITLE
How to enable streaming log with terraform apply 

### ISSUE THREAD

**Issue by gudipudipradeep** [beelit94/python-terraform#63]
apply method **not showing streaming log**. it is showing once it is done. so that I could not able to understand which resource it is creating. when it was hung it will be problem identify  i think.   
but when i am using **terraform apply** command from console i am getting streaming log.

**Comment by Spikeophant** [comment]
Have you used capture_output=False?

**Comment by gudipudipradeep** [comment]
this is my code 
state_location = {"state": "./{0}_state/terraform.tfstate".format(cluster_prefix)}
approve = {"skip_plan": True, "capture_output": True, "raise_on_error": True}
approve.update(state_location)
tf.apply(**approve)

i went through the source code i found following paramters.
capture_output
raise_on_error

but i could not find any streaming   I am using latest version.

**Comment by Spikeophant** [comment]
You should use "capture_output":False, let me know if that does not work for you.

**Comment by Spikeophant** [comment]
Terraform Output
By default, stdout and stderr are captured and returned. This causes the application to appear to hang. To print terraform output in real time, provide the capture_output option with any value other than None. This will cause the output of terraform to be printed to the terminal in real time. The value of stdout and stderr below will be None.

from python_terraform import Terraform
t = Terraform()
return_code, stdout, stderr = t.<cmd_name>(capture_output=False)

It does say any output other than none, but I have found that's not the case, I will make a bug around this.

**Comment by gudipudipradeep** [comment]
Working streaming log but option is little but confuse capture_output=False
