### ISSUE TITLE
Rewrite entire project

### ISSUE THREAD

**Issue by Spikeophant** [beelit94/python-terraform#85]
A coworker and I are going to rewrite this entire project, focusing on tf 12 and fully supporting all functionality therein, as well as decoupling somethings that we feel should not be coupled as tightly as they are in the options building that we have today.  If anyone is interested in working with us on this we feel it will take 2 weekends of work, and one of those will be planning so we can address all bugs in the backlog.  My work is sponsoring us to do this, so he and I will be able to host code reviews online, planning online, etc.

I have been very busy at work and we use this project heavily, we'd like to finally get the improvements I have been wanting to do out the door.  The new python terraform version will rev to 0.12.0, and we'll leave the 0.10 codebase out there for bugfixes if anyone wants to do so.  We will ONLY support TF 12+ in the rewrite however, and ONLY python 3.6+.

Let me know if you are interested and I'll get you info on dates.

Thanks!  Spikeophant

**Comment by AlverezYari** [comment]
@Spikeophant I'm interested in helping out.

**Comment by Spikeophant** [comment]
@AlverezYari  awesome, I am getting a project put together with kanban board and tickets, etc, to get the work planned out.

**Comment by Spikeophant** [comment]
I have been having issues with my day job, I would llike to start this possibly this weekend.  I would like to start by laying out my proposed architecture for project layout, and get some feedback, I was planning to write that up this week however we had some critical software releases I needed to be a part of and was not able to get that time, so Saturday will be blocked out for that for me.

**Comment by samvarankashyap** [comment]
@Spikeophant Would be happy to help. :+1: 
I have good experience with building CI systems using GitHub actions. 
Which I believe would be helpful in the development process.

**Comment by Spikeophant** [comment]
Sounds good most of my expertise in CI systems is aws native or gitlab, so I havent' done a lot on the github side.  Would certainly be useful, right now I just build on my development machine.

**Comment by AlverezYari** [comment]
I've got a lot of experience in this area as well so you guys just let me know how I can help!

**Comment by Spikeophant** [comment]
I setup a kanban board for this project, let me know if you would like to join, it's on Trello.  I started working on the rewrite this weekend, I didn't make a ton of progress yet.  I will work on getting tickets into the kanban for each method under the main classes, tests, etc.

**Comment by AlverezYari** [comment]
Sure, do you have a join link?

**Comment by shawalli** [comment]
@Spikeophant I'd be interested in helping out with this as well

**Comment by davzucky** [comment]
@Spikeophant I'm interested of helping as well. I'm already using it to drive my unit test and would be happy to help you.
I can help you to setup as well CI on circleci if you are interested.
Just came back to your code as I'm starting a new project with terraform

**Comment by Spikeophant** [comment]
Sounds good I have started the work on this, but last weekend was a holiday and I had some stuff going on, I will be back at it this weekend and will add the trello info here and we can start collaborating on what you'd like to do, I can setup zoom meetings or whatever if people would like to plan work.

**Comment by zjpiazza** [comment]
Is there anyone still working on this or is the project officially dead? My current use case is pulling messages from a Kafka topic and pulling out the relevant attributes for TF template, invoking init and apply and communicating if there are any failures back to the source.

**Comment by Spikeophant** [comment]
It is not dead, I am just busy with other stuff, I just changed jobs and hopefully will have more time for this project, I am on a 4x10 schedule at work, so my 5th workweek day will become dedicated to getting this project fixed.  Your current use case seems like it should work with the existing codebase, the rewrite is simply to clean it up, and fix some issues around tf 0.12+, however there are workarounds for things that are funky.  Let me know if I can  help.

**Comment by lhriley** [comment]
@Spikeophant I've been looking forward to this new release for quite a while now. Have you been able to make any progress? Is there a branch / fork available for testing?

**Comment by EvanFabry** [comment]
@Spikeophant, did this get off the ground? I'm interested in contributing/potentially co-owning/managing a fork of this project (or full re-write, whichever you prefer) as well. I've got a pressing use case for this and would probably resort to rolling my own solution if it weren't for this repo, so it'd be great to contribute to yours instead :)

**Comment by Spikeophant** [comment]
This has sort of started, but I didn't get far before I changed jobs and have just been super busy.  I am doing consulting now and haven't had much time to loop back to this project.  I would love to make progress on this and collaborate on how best to rebuild this project.  Let me know what you'd like to do.  I will see if I can add to this repo.

**Comment by EvanFabry** [comment]
I've made very minor changes to the repo in my fork here. https://github.com/EvanFabry/python-terraform

I'd like to make this a mature fork and a proper replacement for this project. There's a lot that needs to be done ofc. In the short term, I'll be setting up CircleCI and adding some basic tests for the sake of my own sanity (mostly enforcing fairly strict compliance with common linters). I'd also like to get rid of reliance on the tempfile library as it's potentially a security issue (if someone lazily passes keys into variables when constructing a python_terraform.Terraform object, those keys are written to disk).

I am certainly onboard with only supporting TF 12, though I've stopped short of attempting to do this by fully re-writing the project.

We will have to either rename this and publish to pypi or find a way to take over this project directly.

@Spikeophant, would you be interested in collaborating over PRs, issues, etc on my fork of this repo? (This also is an open invite, I'll happily review PRs from anyone)

**Comment by aubustou** [comment]
I rewrote nearly everything to support Terraform 0.14 and Python 3.6 (and typing and PEP8 and stuff):

https://github.com/aubustou/python-terraform

**Comment by Spikeophant** [comment]
@aubustou looks good, thank you very much, I am not really using this tool much anymore, and am moving to a different role at a new company, again.  It's been pretty hectic lately so I really appreciate the effort you put in here.
